apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-app
  labels:
    app: my-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-test-app
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
        sidecar.opentelemetry.io/inject: 'true'
      labels:
        app: my-test-app
    spec:
      containers:
      - name: my-test-app
        image: springcommunity/spring-framework-petclinic:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: my-test-app-nodeport-service
spec:
  type: NodePort 
  selector: 
    app: my-test-app
  ports: 
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31233