apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
spec:
  exporter:
    endpoint: http://myapp-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  java:
    # env:
    #   # Required if endpoint is set to 4317.
    #   # Python autoinstrumentation uses http/proto by default
    #   # so data must be sent to 4318 instead of 4317.
    #   - name: OTEL_EXPORTER_OTLP_ENDPOINT
    #     value: http://otel-collector:4318



  