apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: petclinic
            - name: MYSQL_USER
              value: petclinic  
            - name: MYSQL_PASSWORD
              value: petclinic     
          ports:
            - containerPort: 3306
              name: mysql    
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql    
            - name: myapp-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d                               
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-mysql-pv-claim
        - name: myapp-dbcreation-script
          configMap:
            name: myapp-dbcreation-script

---

apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  labels:
    app: mysql
    tier: database
spec:
  selector:
    app: mysql
    tier: database
  ports: 
    - port: 3306
      targetPort: 3306  
  clusterIP: None # This means we are going to use Pod IP   



